trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- bash: ls -R $(System.DefaultWorkingDirectory)
- bash: echo $(Agent.OS)
- bash: echo $(Agent.BuildDirectory)
- bash: echo $(Build.BuildId)
- bash: echo $(Build.BuildNumber)
- bash: echo $(Build.SourceVersion)
- bash: java --version
- bash: node--version
- bash: python --version


